# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  backend:
     container_name: backend-dev
     image: backend
     build:
       context: .
       dockerfile: backend/Dockerfile
     ports:
       - "5000:80"
     environment:
       ASPNETCORE_ENVIRONMENT: Development

  # frontend:
  #   container_name: frontend-dev
  #   image: frontend
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   environment:
  #     - WATCHPACK_POLLING=true
  #     - CHOKIDAR_USEPOLLING=true
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend